# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(215,196,187, 255), stop:1 rgba(215,196,187, 255));")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(560, 260, 761, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.rest1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rest1.setMaximumSize(QtCore.QSize(16777215, 80))
        self.rest1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 180), stop:1 rgba(255, 255, 255, 180));")
        self.rest1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rest1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rest1.setText("")
        self.rest1.setObjectName("rest1")
        self.gridLayout.addWidget(self.rest1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.Dzongkha, QtCore.QLocale.Bhutan))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.rest3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rest3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.rest3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255,255,255,180), stop:1 rgba(255,255,255,180));")
        self.rest3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rest3.setText("")
        self.rest3.setObjectName("rest3")
        self.gridLayout.addWidget(self.rest3, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.Embu, QtCore.QLocale.Kenya))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.rest2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rest2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.rest2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 180), stop:1 rgba(255, 255, 255, 180));")
        self.rest2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rest2.setText("")
        self.rest2.setObjectName("rest2")
        self.gridLayout.addWidget(self.rest2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.Dzongkha, QtCore.QLocale.Bhutan))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.rest4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rest4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.rest4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255,255,255,180), stop:1 rgba(255,255,255,180));")
        self.rest4.setLocale(QtCore.QLocale(QtCore.QLocale.Dzongkha, QtCore.QLocale.Bhutan))
        self.rest4.setText("")
        self.rest4.setObjectName("rest4")
        self.gridLayout.addWidget(self.rest4, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(980, 230, 111, 21))
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(560, 620, 761, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rest30_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rest30_1.setEnabled(True)
        self.rest30_1.setMaximumSize(QtCore.QSize(16777215, 80))
        self.rest30_1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255,255,255,180), stop:1 rgba(255,255,255,180));")
        self.rest30_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rest30_1.setText("")
        self.rest30_1.setObjectName("rest30_1")
        self.verticalLayout.addWidget(self.rest30_1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(890, 760, 101, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(560, 800, 761, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rest30_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.rest30_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.rest30_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255,255,255,180), stop:1 rgba(255,255,255,180));")
        self.rest30_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rest30_3.setText("")
        self.rest30_3.setObjectName("rest30_3")
        self.verticalLayout_2.addWidget(self.rest30_3)
        self.rest30_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.rest30_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.rest30_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255,255,255,180), stop:1 rgba(255,255,255,180));")
        self.rest30_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rest30_2.setText("")
        self.rest30_2.setObjectName("rest30_2")
        self.verticalLayout_2.addWidget(self.rest30_2)
        self.menu = QtWidgets.QComboBox(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(1440, 340, 151, 31))
        self.menu.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menu.setObjectName("menu")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(1590, 340, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.add.setObjectName("add")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1420, 270, 291, 191))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0, 255), stop:1 rgba(0,0,0, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.add.raise_()
        self.frame.raise_()
        self.gridLayoutWidget.raise_()
        self.label_7.raise_()
        self.verticalLayoutWidget.raise_()
        self.label_10.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.menu.raise_()
        self.add.raise_()
        self.rest30_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Working time (25min)"))
        self.label.setText(_translate("MainWindow", "Working time (25min)"))
        self.label_3.setText(_translate("MainWindow", "Working time (25min)"))
        self.label_4.setText(_translate("MainWindow", "Working time (25min)"))
        self.label_7.setText(_translate("MainWindow", "Break time (5min)"))
        self.label_10.setText(_translate("MainWindow", "Long break"))
        self.menu.setItemText(0, _translate("MainWindow", "Cooking & Eatting"))
        self.menu.setItemText(1, _translate("MainWindow", "Washing macnine"))
        self.menu.setItemText(2, _translate("MainWindow", "Door"))
        self.menu.setItemText(3, _translate("MainWindow", "Reminder"))
        self.menu.setItemText(4, _translate("MainWindow", "Boiling tea"))
        self.menu.setItemText(5, _translate("MainWindow", "Custom"))
        self.add.setText(_translate("MainWindow", "Add"))

